# Generated by Django 5.2.1 on 2025-07-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution offering this course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="users.institution",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                help_text="Primary instructor for this course",
                limit_choices_to={"userprofile__role": "faculty"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="course",
            field=models.ForeignKey(
                help_text="Course being enrolled in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academic.course",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="user",
            field=models.ForeignKey(
                help_text="User enrolled in the course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated course (optional for general study groups)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_groups",
                to="academic.course",
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="creator",
            field=models.ForeignKey(
                help_text="User who created the study group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_study_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studygroupmember",
            name="group",
            field=models.ForeignKey(
                help_text="Study group this membership belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="academic.studygroup",
            ),
        ),
        migrations.AddField(
            model_name="studygroupmember",
            name="user",
            field=models.ForeignKey(
                help_text="User who is a member",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["institution", "is_active"],
                name="academic_co_institu_e74ef2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["year", "semester"], name="academic_co_year_eb04ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_code"], name="academic_co_course__518ced_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("institution", "course_code", "semester", "year")},
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["user", "is_active"], name="academic_co_user_id_8f0a83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["course", "role"], name="academic_co_course__a481c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["enrollment_date"], name="academic_co_enrollm_ddd90a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("user", "course")},
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["course", "is_active"], name="academic_st_course__61993f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["creator", "is_active"], name="academic_st_creator_0d9b8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["is_private", "is_active"],
                name="academic_st_is_priv_610e87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["created_at"], name="academic_st_created_3918b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroupmember",
            index=models.Index(
                fields=["group", "is_active"], name="academic_st_group_i_d9302e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroupmember",
            index=models.Index(
                fields=["user", "is_active"], name="academic_st_user_id_321323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroupmember",
            index=models.Index(fields=["role"], name="academic_st_role_f433da_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studygroupmember",
            unique_together={("group", "user")},
        ),
    ]
